# Generated by Django 5.2.7 on 2025-10-26 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_age_userprofile_hobbies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to=settings.AUTH_USER_MODEL, verbose_name='Người thích')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to=settings.AUTH_USER_MODEL, verbose_name='Người được thích')),
            ],
            options={
                'verbose_name': 'Lượt thích',
                'verbose_name_plural': 'Lượt thích',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_user', 'created_at'], name='users_like_to_user_4e9f70_idx'), models.Index(fields=['from_user', 'created_at'], name='users_like_from_us_822834_idx')],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian match')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng 1')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng 2')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user1', 'created_at'], name='users_match_user1_i_c0b069_idx'), models.Index(fields=['user2', 'created_at'], name='users_match_user2_i_2f6db3_idx')],
            },
        ),
    ]
