# Generated by Django 5.2.7 on 2025-10-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_city_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photos',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách các ảnh phụ (tối đa 5 ảnh)'),
        ),
    ]
