# Generated by Django 5.2.7 on 2025-10-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interested_in',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách categories user quan tâm (VD: ["Người yêu", "Bạn trò chuyện"])'),
        ),
    ]
