# Generated by Django 5.2.7 on 2025-10-31 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_interested_in'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lượt thích/không thích', 'verbose_name_plural': 'Lượt thích/không thích'},
        ),
        migrations.AddField(
            model_name='like',
            name='is_like',
            field=models.BooleanField(default=True, help_text='True = like (swipe right), False = dislike (swipe left)'),
        ),
        migrations.AlterField(
            model_name='like',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to=settings.AUTH_USER_MODEL, verbose_name='Người thao tác'),
        ),
        migrations.AlterField(
            model_name='like',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['is_like'], name='users_like_is_like_d122dd_idx'),
        ),
    ]
