// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYDBPQdeHazBNyn6rz6Jeljst-QKwdGjg',
    appId: '1:1014461711829:web:cf4c0167408d6c343fa95c',
    messagingSenderId: '1014461711829',
    projectId: 'app-henho-119c8',
    authDomain: 'app-henho-119c8.firebaseapp.com',
    databaseURL: 'https://app-henho-119c8-default-rtdb.firebaseio.com',
    storageBucket: 'app-henho-119c8.firebasestorage.app',
    measurementId: 'G-09RQT9LFH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDii_RPWsG1h-MGi2widdVcz0aW__N80SM',
    appId: '1:1014461711829:android:880a07f1214598d43fa95c',
    messagingSenderId: '1014461711829',
    projectId: 'app-henho-119c8',
    databaseURL: 'https://app-henho-119c8-default-rtdb.firebaseio.com',
    storageBucket: 'app-henho-119c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY7uFsQWHP2g3Eu0NZ7QnA3A_kXe8VeWI',
    appId: '1:1014461711829:ios:4b4524cee93194353fa95c',
    messagingSenderId: '1014461711829',
    projectId: 'app-henho-119c8',
    databaseURL: 'https://app-henho-119c8-default-rtdb.firebaseio.com',
    storageBucket: 'app-henho-119c8.firebasestorage.app',
    iosBundleId: 'com.example.appHenho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY7uFsQWHP2g3Eu0NZ7QnA3A_kXe8VeWI',
    appId: '1:1014461711829:ios:4b4524cee93194353fa95c',
    messagingSenderId: '1014461711829',
    projectId: 'app-henho-119c8',
    databaseURL: 'https://app-henho-119c8-default-rtdb.firebaseio.com',
    storageBucket: 'app-henho-119c8.firebasestorage.app',
    iosBundleId: 'com.example.appHenho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYDBPQdeHazBNyn6rz6Jeljst-QKwdGjg',
    appId: '1:1014461711829:web:d4784a39bb42119c3fa95c',
    messagingSenderId: '1014461711829',
    projectId: 'app-henho-119c8',
    authDomain: 'app-henho-119c8.firebaseapp.com',
    databaseURL: 'https://app-henho-119c8-default-rtdb.firebaseio.com',
    storageBucket: 'app-henho-119c8.firebasestorage.app',
    measurementId: 'G-ENE5FX8J2T',
  );
}
